# Site settings
title: Kabir Abdulmajeed 
description: Kbmajeed Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kabir Abdulmajeed
user_description: 
user_title: Data Scientist
email: kbmajeed1@gmail.com
twitter_username: kbmajeed1
github_username:  kbmajeed
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
